#!/bin/bash
#set -v on

if [ $# -lt 1 ]; then
echo "Parameters too few"
exit
fi

THEPATH=$1
echo "The path is: " $THEPATH


TheTime=5.1300000000e-4
OutTime=1.1000000000e-5
FocusTime1=1.0000000000e-9
FocusTime2=1.0000000000e-7
FocusTime3=1.0000000000e-5

cd $THEPATH

TheCtrlFile="CtrlFile.dat"

touch $TheCtrlFile
  : > $TheCtrlFile

echo "&CTLF
  &COMMSUBCTL
    &BOX box in one test = 800 , total num = 800 , independent = 1
    &RANDSEED random number seed = 8845, 63879542
  &ENDSUBCTL

  &ANALYSUBCTL
    &JOBSEL the start job index = 1, the end job index = 1, the interval of jobs = 1
    &TSECTIONSEL the start time section index = 0, the end time section = 20, the interval of sections = 1
    &CFGSEL the start configure index = 0, the end configure index = 1000 , the interval of configure = 1
    &BOXSEL the start box index = 1, the end of the box index = 800, the interval of box = 1
  &ENDSUBCTL
  
  &SECTSUBCTL #1
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL
        &TERMINATE Maxma simulation flag = 1, the time = 1.0D-11                 		     ! flag = 0 stans for by steps,flag = 1 by time(s)

	!&FOCUSETIME The focused timepoints are = 1.2D-12 , 2.6D-12 , 4.7D-12 , 9.9D-12		     ! give the timepoints that needs to be focused
                       
        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time


	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 10000                           ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-12              ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 100000 , the interval for each box = 100000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 100000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #1

  &SECTSUBCTL #2
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL
        &TERMINATE Maxma simulation flag = 1, the time = 1.0D-10				     ! flag = 0 stans for by steps,flag = 1 by time(s)

	!&FOCUSETIME The focused timepoints are = 1.2D-12 , 2.6D-12 , 4.7D-12 , 9.9D-12		     ! give the timepoints that needs to be focused
                       
        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time

	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 10000                           ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-11              ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 10000 , the interval for each box = 10000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 10000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #2


  &SECTSUBCTL #3
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL
        &TERMINATE Maxma simulation flag = 1, the time = 1.0D-9					     ! flag = 0 stans for by steps,flag = 1 by time(s)

	!&FOCUSETIME The focused timepoints are = 1.2D-12 , 2.6D-12 , 4.7D-12 , 9.9D-12		     ! give the timepoints that needs to be focused
                       
        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time

	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 10000                           ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-10              ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 10000 , the interval for each box = 10000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 10000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #3

  &SECTSUBCTL #4
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL
        &TERMINATE Maxma simulation flag = 1, the time = 1.0D-8					     ! flag = 0 stans for by steps,flag = 1 by time(s)

	!&FOCUSETIME The focused timepoints are = 1.2D-12 , 2.6D-12 , 4.7D-12 , 9.9D-12		     ! give the timepoints that needs to be focused
                       
        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time

	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 10000                           ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-9               ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 10000 , the interval for each box = 10000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 10000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #4

  &SECTSUBCTL #5
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL
        &TERMINATE Maxma simulation flag = 1, the time = 1.0D-7					     ! flag = 0 stans for by steps,flag = 1 by time(s)

	!&FOCUSETIME The focused timepoints are = 1.2D-12 , 2.6D-12 , 4.7D-12 , 9.9D-12		     ! give the timepoints that needs to be focused
                       
        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time

	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 100000                          ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-8               ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 10000 , the interval for each box = 10000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 10000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #5

  &SECTSUBCTL #6
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL
        &TERMINATE Maxma simulation flag = 1, the time = 1.0D-6					     ! flag = 0 stans for by steps,flag = 1 by time(s)

	!&FOCUSETIME The focused timepoints are = 1.2D-12 , 2.6D-12 , 4.7D-12 , 9.9D-12		     ! give the timepoints that needs to be focused
                       
        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time

	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 100000                          ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-7               ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 10000 , the interval for each box = 10000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 10000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #6

  &SECTSUBCTL #7
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL
        &TERMINATE Maxma simulation flag = 1, the time = 1.0D-5					     ! flag = 0 stans for by steps,flag = 1 by time(s)

	!&FOCUSETIME The focused timepoints are = 1.2D-12 , 2.6D-12 , 4.7D-12 , 9.9D-12		     ! give the timepoints that needs to be focused
                       
        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time

	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 100000                          ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-6               ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 10000 , the interval for each box = 10000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 10000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #7

  &SECTSUBCTL #8
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL
        &TERMINATE Maxma simulation flag = 1, the time = 1.0D-4					     ! flag = 0 stans for by steps,flag = 1 by time(s)

	!&FOCUSETIME The focused timepoints are = 1.2D-12 , 2.6D-12 , 4.7D-12 , 9.9D-12		     ! give the timepoints that needs to be focused
                       
        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time

	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 100000                          ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-5               ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 10000 , the interval for each box = 10000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 10000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #8
" >> $TheCtrlFile

for((IBatch=1;IBatch<=8;IBatch++))
do

echo "  &SECTSUBCTL #"$(echo $IBatch 8 |awk '{printf "%d", $1+$2}')"
    &TEMPSUBCTL
        &TEMPERATURE SYSTEM SIMULATION TEMPERATURE = 300 (K)
    &ENDSUBCTL

    &BOUNDSUBCTL
        &PERIDIC If use periodic boundary condition: X = 1, Y = 1, Z = 1
    &ENDSUBCTL
  
    &NEIGHBSUBCTL   
	&STRATEGY   The parameter determine the way to update neighbor-List = 1         ! 1 for NNearest way, 2 for cut-off radium way
	&MAXNB   maxmun number of neighbore for an diffusor = 1
	&UPDATEFRE  The parameter determine when the neighbore list to be updated = 1 ! If the value >=1 then the NeighborList would be updated for each UPDATEFRE steps
                                                                                         ! If the value <1 then the NeighborList would be updated while the count rate drop UPDATEFRE
	&CUTREGIONEXTEND The cut-off region expand = 4					 ! It is used for neighbor-list cut-off radium way, as the cut-off radium is determined by the average 
                                                                                         ! seperatment between diffusor, CUTREGIONEXTEND is used to expand the cut-off radium to serval times
    &ENDSUBCTL

    &IMPLANTSUBCTL
        &IMPLANTID The used implantation group in current time section = 4
    &ENDSUBCTL
    
    &TIMESUBCTL" >> $TheCtrlFile

echo "        &TERMINATE Maxma simulation flag = 1, the time ="$(echo "$TheTime $OutTime $IBatch"|awk '{printf "%.10e", $1*$3+$2}')"					     ! flag = 0 stans for by steps,flag = 1 by time(s)" >> $TheCtrlFile

echo "        &FOCUSETIME The focused timepoints are = "$(echo "$TheTime $IBatch $FocusTime1 $FocusTime2 $FocusTime3"|awk '{printf "%.10e ,%.10e ,%.10e", $1*$2+$3, $1*$2+$4, $1*$2+$5}')"		     ! give the timepoints that needs to be focused" >> $TheCtrlFile
                       
echo "        &TSTEPSTRATEGY  The update time-step strategy = 3, the correspond value = 2.76D-13           ! flag = 0 the time step is determined by average distance of nearest cluster,correspond value for enlarge-scale
        											     ! flag = 1 is by fixed time-step, correspond value for the step time
        											     ! flag = 2 the time step is determined by volume average distance and suppose the clusters distribute
												     ! flag = 3 the time step is determined by NNDR algorithm, the corresponded value is the lower limit
											 	     ! flag = 4 the time step is determined by NNDR algorithm lastpassage Integer lowerlimit stragegy, the corresponded value is the lower limit time

	&UPDATESTATISTIC  Use fixd step flag = 0, the correspond value = 100000                          ! flag = 0 stans for by steps,flag = 1 by time(s)
  	
        &OUTPUT_CONF     Output instant configuration flag = 1 , the interval = 1.0D-4               ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &OUTPUT_SC       Output instant size statistic information flag = 0 , the interval for integral box = 10000 , the interval for each box = 10000      
												     ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
	&OUTPUT_FUNCS    Output instant function statistic information flag = 1, the interval = 10000  ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
        &SAVE            Output instant information for restart flag = 1,the interval = 100          ! flag = 0 for output each interval steps,flag = 1 for output each interval time(s), 2 by time magnification
    &ENDSUBCTL


    &ADDONDATA
	&DUMPLICATEBOX If use the dumplicate box strategy = 0     ! 1 for use dumplicate box strategy while clusters number drop to some percentage, 0 for not
	&CHECKNCLUSTERS  If check cluster number conservation = 0 ! 1 for check cluster number conservation, 0 for not
	&SURDIF	 THE Surface Diffusion coefficiens, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&GBSURDIF THE Surface Diffusion coefficiens in GB, prefactor (cm^2/s) and ES(ev): 3.7D-4 , 0.92 , 3.7D-4 , 0.92 , 3.7D-4 , 0.92
	&SIZEPARAM Size dependent parameter Gama =  4.D0
    &ENDSUBCTL

    &MODELDATA
	&SURFE THE SURFACE ENERGY OF A BUBBLE (m_SURFE) = 3890             ! (ERG/CM^2))  
	&BiasFactor = 1.15  
	&Corrections 0.D0 (cm)
	&R0 1.37D-8 (cm)
	&R1 3.D-8 (cm)
    &ENDSUBCTL	

  &ENDSUBCTL #"$(echo $IBatch 8 |awk '{printf "%d", $1+$2}')"
" >> $TheCtrlFile

done

echo "&ENDCTLF" >> $TheCtrlFile
