!
!  MCLIB_TimeProfile.F90
!
!  Free-Format Fortran Source File
!  Generated by PGI Visual Fortran(R)
!  10/12/2017 11:28:07 PM

module MCLIB_TimeProfile

  implicit none

   integer,private::m_OUTPUTUNIT_TimeProfile = 1
   integer,private::minu2MicroSecond = 60000
   integer,private::hour2MicroSecond = 3600000
   integer,private::day2MicroSecond  = 86400000

   integer,private::m_flushed = 0

   !----
   integer::N_Invoke_Cal_Neighbor_CPU = 0
   integer::N_Invoke_Cal_Neighbor_GPU = 0

   real::T_FullCalTime_Start = 0
   real::T_FullCalTime = 0

   !--------BUBBLEGROWTH_COMMON----------
   real::T_LoadSimulationParameter = 0
   real::T_LoadMultiBox = 0
   real::T_LoadDistributionParameter = 0
   real::T_LoadCtrlParameter = 0
   real::T_LoadPhysicsParameter = 0
   real::T_LoadOutPutCtrlParameter = 0
   real::T_LoadPreviousStatus = 0
   real::T_Init_System = 0
   real::T_Init_New = 0
   real::T_Init_Old = 0
   real::T_Load_Previous_VisualData = 0
   real::T_Load_Previous_SwapData = 0
   real::T_Load_Previous_StatisticData = 0
   real::T_Load_Old_FORMATTED = 0
   real::T_Load_Old_UNFORMATTED = 0
   real::T_Init_Depth_Dis_LAY = 0
   real::T_Init_Depth_Dis_Gauss = 0
   real::T_UpdateTimeStep = 0
   real::T_OutputIntermediateStatus = 0
   real::T_OutputConfigure = 0
   real::T_OutputConfigureUnformat = 0
   real::T_OutputStatistics = 0
   real::T_GetStatistic_AllBoxs = 0
   real::T_GetStatistics_SingleBox = 0
   real::T_GetSizeStatistics_SingleBox_New = 0

   real::T_LoadSimulationParameter_Start = 0
   real::T_LoadMultiBox_Start = 0
   real::T_LoadDistributionParameter_Start = 0
   real::T_LoadCtrlParameter_Start = 0
   real::T_LoadPhysicsParameter_Start = 0
   real::T_LoadOutPutCtrlParameter_Start = 0
   real::T_LoadPreviousStatus_Start = 0
   real::T_Init_System_Start = 0
   real::T_Init_New_Start = 0
   real::T_Init_Old_Start = 0
   real::T_Load_Previous_VisualData_Start = 0
   real::T_Load_Previous_SwapData_Start = 0
   real::T_Load_Previous_StatisticData_Start = 0
   real::T_Load_Old_FORMATTED_Start = 0
   real::T_Load_Old_UNFORMATTED_Start = 0
   real::T_Init_Depth_Dis_LAY_Start = 0
   real::T_Init_Depth_Dis_Gauss_Start = 0
   real::T_UpdateTimeStep_Start = 0
   real::T_OutputIntermediateStatus_Start = 0
   real::T_OutputConfigure_Start = 0
   real::T_OutputConfigureUnformat_Start = 0
   real::T_OutputStatistics_Start = 0
   real::T_GetStatistic_AllBoxs_Start = 0
   real::T_GetStatistics_SingleBox_Start = 0
   real::T_GetSizeStatistics_SingleBox_New_Start = 0
   !--------MCLIB_BUBBLE_EVOLUTION_CPU---------
   real::T_Init_System_CPU = 0
   real::T_Release_Growth_CPU = 0
   real::T_Growth_FixBox_CPU = 0
   real::T_FOR_ONE_STEP_CPU = 0
   real::T_Bubbles_WalkOneStep_CPU = 0
   real::T_Bubbles_Merge_CPU = 0
   real::T_Bubbles_Merge_CPU_WithoutNeighborList = 0
   real::T_Bubbles_UpdateStatistic_CPU = 0

   real::T_Init_System_CPU_Start = 0
   real::T_Release_Growth_CPU_Start = 0
   real::T_Growth_FixBox_CPU_Start = 0
   real::T_FOR_ONE_STEP_CPU_Start = 0
   real::T_Bubbles_WalkOneStep_CPU_Start = 0
   real::T_Bubbles_Merge_CPU_Start = 0
   real::T_Bubbles_Merge_CPU_WithoutNeighborList_Start = 0
   real::T_Bubbles_UpdateStatistic_CPU_Start = 0
   !--------MCLIB_BUBBLE_EVOLUTION_GPU---------
   real::T_Init_System_GPU = 0
   real::T_Release_Growth_GPU = 0
   real::T_Initital_Growth_FixBox_GPU = 0
   real::T_Growth_FixBox_GPU = 0
   real::T_FOR_ONE_STEP_GPU0 = 0
   real::T_FOR_ONE_STEP_GPU1 = 0
   real::T_FOR_ONE_STEP_GPU2 = 0
   real::T_FOR_ONE_STEP_GPU3 = 0
   real::T_FOR_ONE_STEP_GPU4 = 0
   real::T_copyOutMergeTable = 0

   real::T_Init_System_GPU_Start = 0
   real::T_Release_Growth_GPU_Start = 0
   real::T_Initital_Growth_FixBox_GPU_Start = 0
   real::T_Growth_FixBox_GPU_Start = 0
   real::T_FOR_ONE_STEP_GPU0_Start = 0
   real::T_FOR_ONE_STEP_GPU1_Start = 0
   real::T_FOR_ONE_STEP_GPU2_Start = 0
   real::T_FOR_ONE_STEP_GPU3_Start = 0
   real::T_FOR_ONE_STEP_GPU4_Start = 0
   real::T_copyOutMergeTable_Start = 0
   !--------MCLIB_CAL_NEIGHBOR_LIST----------
   real::T_Cal_Neighbore_Table_Old_CPU = 0
   real::T_Cal_Neighbore_Table_NNearest_CPU = 0

   real::T_Cal_Neighbore_Table_Old_CPU_Start = 0
   real::T_Cal_Neighbore_Table_NNearest_CPU_Start = 0
   !---------MCLIB_TYPEDEF_NEIGHBOR_LIST---------
   real::T_Allocate_NEIGHBOR_LIST = 0
   real::T_PTR_Allocate_NEIGHBOR_LIST = 0
   real::T_CLEAR_NEIGHBOR_LIST = 0
   real::T_PTR_CLEAR_NEIGHBOR_LIST  = 0
   real::T_STATUS_NEIGHBOR_LIST_Allocated = 0

   real::T_Allocate_NEIGHBOR_LIST_Start = 0
   real::T_PTR_Allocate_NEIGHBOR_LIST_Start = 0
   real::T_CLEAR_NEIGHBOR_LIST_Start = 0
   real::T_PTR_CLEAR_NEIGHBOR_LIST_Start  = 0
   real::T_STATUS_NEIGHBOR_LIST_Allocated_Start = 0
   !-------------MCLIB_UTILITIES------------
   real::T_RAND = 0
   real::T_RAND_PUTSEED = 0
   real::T_RAND_GETSEED = 0
   real::T_RGAUSS0 = 0
   real::T_RGAUSS = 0
   real::T_ran0 = 0
   real::T_ran1 = 0
   real::T_ran2 = 0
   real::T_ran3 = 0
   real::T_ran4 = 0
   real::T_psdes = 0
   real::T_gasdev = 0
   real::T_SCALEDCFunction1 = 0
   real::T_GABQ = 0
   real::T_SPLINE = 0
   real::T_INTEG = 0
   real::T_FINDI = 0
   real::T_RQSORT = 0
   real::T_DRAFT_GRAPH = 0
   real::T_Calc_RCUT_Old = 0
   real::T_Calc_RCUT_DIF = 0

   real::T_RAND_Start = 0
   real::T_RAND_PUTSEED_Start = 0
   real::T_RAND_GETSEED_Start = 0
   real::T_RGAUSS0_Start = 0
   real::T_RGAUSS_Start = 0
   real::T_ran0_Start = 0
   real::T_ran1_Start = 0
   real::T_ran2_Start = 0
   real::T_ran3_Start = 0
   real::T_ran4_Start = 0
   real::T_psdes_Start = 0
   real::T_gasdev_Start = 0
   real::T_SCALEDCFunction1_Start = 0
   real::T_GABQ_Start = 0
   real::T_SPLINE_Start = 0
   real::T_INTEG_Start = 0
   real::T_FINDI_Start = 0
   real::T_RQSORT_Start = 0
   real::T_DRAFT_GRAPH_Start = 0
   real::T_Calc_RCUT_Old_Start = 0
   real::T_Calc_RCUT_DIF_Start = 0
   !-------MCLIB_CAL_NEIGHBOR_LIST_GPU------------
   real::T_INIT_DEV_Cal_Neighbore_Table = 0
   real::T_Cal_Neighbore_Table_GPU_Old = 0
   real::T_Cal_Neighbore_Table_GPU_Nearest = 0

   real::T_INIT_DEV_Cal_Neighbore_Table_Start = 0
   real::T_Cal_Neighbore_Table_GPU_Old_Start = 0
   real::T_Cal_Neighbore_Table_GPU_Nearest_Start = 0
   !------------MCLIB_GLOBAL_GPU----------------
   real::T_Init_Device_Setting = 0

   real::T_Init_Device_Setting_Start = 0
   !------------MCLIB_Utilities_GPU-------------
   real::T_copyNeighborListFromGPUToCPU = 0
   real::T_copyInClustersSync = 0
   real::T_copyOutClustersSync = 0
   real::T_copyOutActiveIndexSync = 0
   real::T_getBlockFilledSize = 0

   real::T_copyNeighborListFromGPUToCPU_Start = 0
   real::T_copyInClustersSync_Start = 0
   real::T_copyOutClustersSync_Start = 0
   real::T_copyOutActiveIndexSync_Start = 0
   real::T_getBlockFilledSize_Start = 0
   !------------DRAND32----------------
   real::T_DRAND32_PUTSEED = 0
   real::T_DRAND32_GETSEED = 0
   real::T_DRAND32 = 0
   real::T_DRAND32_S = 0

   real::T_DRAND32_PUTSEED_Start = 0
   real::T_DRAND32_GETSEED_Start = 0
   real::T_DRAND32_Start = 0
   real::T_DRAND32_S_Start = 0
   !-----------DRAND32SEEDLIB-----------
   real::T_GetSeed_RAND32SEEDLIB = 0

   real::T_GetSeed_RAND32SEEDLIB_Start = 0
  !****************************************************************

  contains
  !***************Time Debug*******************************************
  subroutine Time_Start(FUNCTIME_START)
    implicit none
    !----------Local Vars---------
    character(LEN = 12) REAL_CLOCK1(3), REAL_CLOCK2(3)
    integer DATE_TIME1(8)
    real::FUNCTIME_START
    !----------Body---------------
    CALL DATE_AND_TIME(REAL_CLOCK1(1), REAL_CLOCK1(2), REAL_CLOCK1(3), DATE_TIME1)
    FUNCTIME_START = DATE_TIME1(8) + &
                     DATE_TIME1(7)*1000 + &
                     DATE_TIME1(6)*minu2MicroSecond + &
                     DATE_TIME1(5)*hour2MicroSecond + &
                     DATE_TIME1(3)*day2MicroSecond

  end subroutine

  !*********************************************************************
  subroutine Time_Accumulate(FUNCTIME_START,FUNCTIME)
    implicit none
    !-----------Dummy Vars----------
    real::FUNCTIME_START,FUNCTIME
    !----------Local Vars---------
    character(LEN = 12)::REAL_CLOCK1(3), REAL_CLOCK2(3)
    integer::DATE_TIME1(8)
    real::ENDTIME
    !----------Body---------------
    CALL DATE_AND_TIME(REAL_CLOCK1(1), REAL_CLOCK1(2), REAL_CLOCK1(3), DATE_TIME1)
    ENDTIME = DATE_TIME1(8) + &
              DATE_TIME1(7)*1000 + &
              DATE_TIME1(6)*minu2MicroSecond + &
              DATE_TIME1(5)*hour2MicroSecond + &
              DATE_TIME1(3)*day2MicroSecond

    FUNCTIME = FUNCTIME + ENDTIME - FUNCTIME_START

  end subroutine Time_Accumulate

  !*********************************************************************
  subroutine InitOutPutTimeProfile(Ctlfilename)
    implicit none
    !---Dummy Vars---
    character*256,intent(in)::Ctlfilename
    !---Local Vars---
    logical::opened
    character*256::outfilename_TimeProfile
    !---Body---
    !---Define the file that output the size statistic information
    outfilename_TimeProfile = Ctlfilename(1:LEN_TRIM(Ctlfilename))//"_Functions.profile"
    DO m_OUTPUTUNIT_TimeProfile = 10, 99
       INQUIRE(UNIT=m_OUTPUTUNIT_TimeProfile, OPENED=opened)
       if(.not.opened) exit
    END DO

    OPEN(UNIT=m_OUTPUTUNIT_TimeProfile, file = outfilename_TimeProfile)
    write(m_OUTPUTUNIT_TimeProfile, fmt="(' ',A10,',',2(A15,','),180(A38,','))") "Step",                    &
                                                                "Time(s)",                                  &
                                                                "FullCalTime",                              &
                                                                !--------BUBBLEGROWTH_COMMON----------
                                                                "LoadSimulationParameter",                  &
                                                                "LoadMultiBox",                             &
                                                                "LoadDistributionParameter",                &
                                                                "LoadCtrlParameter",                        &
                                                                "LoadPhysicsParameter",                     &
                                                                "LoadOutPutCtrlParameter",                  &
                                                                "LoadPreviousStatus",                       &
                                                                "Init_System",                              &
                                                                "Init_New",                                 &
                                                                "Init_Old",                                 &
                                                                "Load_Previous_VisualData",                 &
                                                                "Load_Previous_SwapData",                   &
                                                                "Load_Previous_StatisticData",              &
                                                                "Load_Old_FORMATTED",                       &
                                                                "Load_Old_UNFORMATTED",                     &
                                                                "Init_Depth_Dis_LAY",                       &
                                                                "Init_Depth_Dis_Gauss",                     &
                                                                "UpdateTimeStep",                           &
                                                                "OutputIntermediateStatus",                 &
                                                                "OutputConfigure",                          &
                                                                "OutputConfigureUnformat",                  &
                                                                "OutputStatistics",                         &
                                                                "GetStatistic_AllBoxs",                     &
                                                                "GetStatistics_SingleBox",                  &
                                                                "GetSizeStatistics_SingleBox_New",          &
                                                                !--------MCLIB_BUBBLE_EVOLUTION_CPU---------
                                                                "Init_System_CPU",                          &
                                                                "Release_Growth_CPU",                       &
                                                                "Growth_FixBox_CPU",                        &
                                                                "FOR_ONE_STEP_CPU",                         &
                                                                "Bubbles_WalkOneStep_CPU",                  &
                                                                "Bubbles_Merge_CPU",                        &
                                                                "Bubbles_Merge_CPU_WithoutNeighborList",    &
                                                                "Bubbles_UpdateStatistic_CPU",              &
                                                                !--------MCLIB_BUBBLE_EVOLUTION_GPU---------
                                                                "Init_System_GPU",                          &
                                                                "Release_Growth_GPU",                       &
                                                                "Initital_Growth_FixBox_GPU",               &
                                                                "Growth_FixBox_GPU",                        &
                                                                "FOR_ONE_STEP_GPU0",                        &
                                                                "FOR_ONE_STEP_GPU1",                        &
                                                                "FOR_ONE_STEP_GPU2",                        &
                                                                "FOR_ONE_STEP_GPU3",                        &
                                                                "FOR_ONE_STEP_GPU4",                        &
                                                                "copyOutMergeTable",                        &
                                                                !--------MCLIB_CAL_NEIGHBOR_LIST----------
                                                                "Cal_Neighbore_Table_Old_CPU",              &
                                                                "Cal_Neighbore_Table_NNearest_CPU",         &
                                                                !---------MCLIB_TYPEDEF_NEIGHBOR_LIST---------
                                                                "Allocate_NEIGHBOR_LIST",                   &
                                                                "PTR_Allocate_NEIGHBOR_LIST",               &
                                                                "CLEAR_NEIGHBOR_LIST",                      &
                                                                "PTR_CLEAR_NEIGHBOR_LIST",                  &
                                                                "STATUS_NEIGHBOR_LIST_Allocated",           &
                                                                !-------------MCLIB_UTILITIES------------
                                                                "RAND",                                     &
                                                                "RAND_PUTSEED",                             &
                                                                "RAND_GETSEED",                             &
                                                                "RGAUSS0",                                  &
                                                                "RGAUSS",                                   &
                                                                "ran0",                                     &
                                                                "ran1",                                     &
                                                                "ran2",                                     &
                                                                "ran3",                                     &
                                                                "ran4",                                     &
                                                                "psdes",                                    &
                                                                "gasdev",                                   &
                                                                "SCALEDCFunction1",                         &
                                                                "GABQ",                                     &
                                                                "SPLINE",                                   &
                                                                "INTEG",                                    &
                                                                "FINDI",                                    &
                                                                "RQSORT",                                   &
                                                                "DRAFT_GRAPH",                              &
                                                                "Calc_RCUT_Old",                            &
                                                                "Calc_RCUT_DIF",                            &
                                                                !-------MCLIB_CAL_NEIGHBOR_LIST_GPU------------
                                                                "INIT_DEV_Cal_Neighbore_Table",             &
                                                                "Cal_Neighbore_Table_GPU_Old",              &
                                                                "Cal_Neighbore_Table_GPU_Nearest",          &
                                                                !------------MCLIB_GLOBAL_GPU----------------
                                                                "Init_Device_Setting",                      &
                                                                !------------MCLIB_Utilities_GPU-------------
                                                                "copyNeighborListFromGPUToCPU",             &
                                                                "copyInClustersSync",                       &
                                                                "copyOutClustersSync",                      &
                                                                "copyOutActiveIndexSync",                   &
                                                                "getBlockFilledSize",                       &
                                                                !------------DRAND32----------------
                                                                "DRAND32_PUTSEED",                          &
                                                                "DRAND32_GETSEED",                          &
                                                                "DRAND32",                                  &
                                                                "DRAND32_S",                                &
                                                                !-----------DRAND32SEEDLIB-----------
                                                                "GetSeed_RAND32SEEDLIB"

     call Time_Start(T_FullCalTime_Start)

     return
  end subroutine InitOutPutTimeProfile

  !*********************************************************
  subroutine CloseOutPutTimeProfile(TSTEP,CURTIME)
    !***Purpose:  to close the opened unit of time profile-file and output the last one
    !     TSTEP:  current time step
    !     CURTIME:current evolution time
    implicit none
    !---Dummy Vars----
    integer,intent(in)::TSTEP
    real,intent(in)::CURTIME

    !---Body---
    call OutPutTimeDebug(TSTEP,CURTIME)

    close(m_OUTPUTUNIT_TimeProfile)
    return
  end subroutine CloseOutPutTimeProfile
  !*********************************************************
  subroutine OutPutTimeDebug(TSTEP,CURTIME,OUTPROFILETIMESTEP)
    !***Purpose: to output the time profile for each function
    !     TSTEP:  current time step
    !     CURTIME:current evolution time
    implicit none
    !---Dummy Vars----
    integer,intent(in)::TSTEP
    real,intent(in)::CURTIME
    real,optional::OUTPROFILETIMESTEP
    !---Local Vars----
    character(LEN = 12)::REAL_CLOCK1(3)
    integer::DATE_TIME1(8)
    real::TIME_MS

    !----------Body---------------
    CALL DATE_AND_TIME(REAL_CLOCK1(1), REAL_CLOCK1(2), REAL_CLOCK1(3), DATE_TIME1)
    TIME_MS = DATE_TIME1(8) + &
              DATE_TIME1(7)*1000 + &
              DATE_TIME1(6)*minu2MicroSecond + &
              DATE_TIME1(5)*hour2MicroSecond + &
              DATE_TIME1(3)*day2MicroSecond

    T_FullCalTime = TIME_MS - T_FullCalTime_Start

    write(m_OUTPUTUNIT_TimeProfile, fmt="(1X,I10,1X,2(ES15.3,1X),180(F38.3,1x))")   TSTEP,                  &
                                                                               CURTIME,                     &
                                                                               T_FullCalTime,               &
                                                                !--------BUBBLEGROWTH_COMMON----------
                                                                T_LoadSimulationParameter,                  &
                                                                T_LoadMultiBox,                             &
                                                                T_LoadDistributionParameter,                &
                                                                T_LoadCtrlParameter,                        &
                                                                T_LoadPhysicsParameter,                     &
                                                                T_LoadOutPutCtrlParameter,                  &
                                                                T_LoadPreviousStatus,                       &
                                                                T_Init_System,                              &
                                                                T_Init_New,                                 &
                                                                T_Init_Old,                                 &
                                                                T_Load_Previous_VisualData,                 &
                                                                T_Load_Previous_SwapData,                   &
                                                                T_Load_Previous_StatisticData,              &
                                                                T_Load_Old_FORMATTED,                       &
                                                                T_Load_Old_UNFORMATTED,                     &
                                                                T_Init_Depth_Dis_LAY,                       &
                                                                T_Init_Depth_Dis_Gauss,                     &
                                                                T_UpdateTimeStep,                           &
                                                                T_OutputIntermediateStatus,                 &
                                                                T_OutputConfigure,                          &
                                                                T_OutputConfigureUnformat,                  &
                                                                T_OutputStatistics,                         &
                                                                T_GetStatistic_AllBoxs,                     &
                                                                T_GetStatistics_SingleBox,                  &
                                                                T_GetSizeStatistics_SingleBox_New,          &
                                                                !--------MCLIB_BUBBLE_EVOLUTION_CPU---------
                                                                T_Init_System_CPU,                          &
                                                                T_Release_Growth_CPU,                       &
                                                                T_Growth_FixBox_CPU,                        &
                                                                T_FOR_ONE_STEP_CPU,                         &
                                                                T_Bubbles_WalkOneStep_CPU,                  &
                                                                T_Bubbles_Merge_CPU,                        &
                                                                T_Bubbles_Merge_CPU_WithoutNeighborList,    &
                                                                T_Bubbles_UpdateStatistic_CPU,              &
                                                                !--------MCLIB_BUBBLE_EVOLUTION_GPU---------
                                                                T_Init_System_GPU,                          &
                                                                T_Release_Growth_GPU,                       &
                                                                T_Initital_Growth_FixBox_GPU,               &
                                                                T_Growth_FixBox_GPU,                        &
                                                                T_FOR_ONE_STEP_GPU0,                        &
                                                                T_FOR_ONE_STEP_GPU1,                        &
                                                                T_FOR_ONE_STEP_GPU2,                        &
                                                                T_FOR_ONE_STEP_GPU3,                        &
                                                                T_FOR_ONE_STEP_GPU4,                        &
                                                                T_copyOutMergeTable,                        &
                                                                !--------MCLIB_CAL_NEIGHBOR_LIST----------
                                                                T_Cal_Neighbore_Table_Old_CPU,              &
                                                                T_Cal_Neighbore_Table_NNearest_CPU,         &
                                                                !---------MCLIB_TYPEDEF_NEIGHBOR_LIST---------
                                                                T_Allocate_NEIGHBOR_LIST,                   &
                                                                T_PTR_Allocate_NEIGHBOR_LIST,               &
                                                                T_CLEAR_NEIGHBOR_LIST,                      &
                                                                T_PTR_CLEAR_NEIGHBOR_LIST,                  &
                                                                T_STATUS_NEIGHBOR_LIST_Allocated,           &
                                                                !-------------MCLIB_UTILITIES------------
                                                                T_RAND,                                     &
                                                                T_RAND_PUTSEED,                             &
                                                                T_RAND_GETSEED,                             &
                                                                T_RGAUSS0,                                  &
                                                                T_RGAUSS,                                   &
                                                                T_ran0,                                     &
                                                                T_ran1,                                     &
                                                                T_ran2,                                     &
                                                                T_ran3,                                     &
                                                                T_ran4,                                     &
                                                                T_psdes,                                    &
                                                                T_gasdev,                                   &
                                                                T_SCALEDCFunction1,                         &
                                                                T_GABQ,                                     &
                                                                T_SPLINE,                                   &
                                                                T_INTEG,                                    &
                                                                T_FINDI,                                    &
                                                                T_RQSORT,                                   &
                                                                T_DRAFT_GRAPH,                              &
                                                                T_Calc_RCUT_Old,                            &
                                                                T_Calc_RCUT_DIF,                            &
                                                                !-------MCLIB_CAL_NEIGHBOR_LIST_GPU------------
                                                                T_INIT_DEV_Cal_Neighbore_Table,             &
                                                                T_Cal_Neighbore_Table_GPU_Old,              &
                                                                T_Cal_Neighbore_Table_GPU_Nearest,          &
                                                                !------------MCLIB_GLOBAL_GPU----------------
                                                                T_Init_Device_Setting,                      &
                                                                !------------MCLIB_Utilities_GPU-------------
                                                                T_copyNeighborListFromGPUToCPU,             &
                                                                T_copyInClustersSync,                       &
                                                                T_copyOutClustersSync,                      &
                                                                T_copyOutActiveIndexSync,                   &
                                                                T_getBlockFilledSize,                       &
                                                                !------------DRAND32----------------
                                                                T_DRAND32_PUTSEED,                          &
                                                                T_DRAND32_GETSEED,                          &
                                                                T_DRAND32,                                  &
                                                                T_DRAND32_S,                                &
                                                                !-----------DRAND32SEEDLIB-----------
                                                                T_GetSeed_RAND32SEEDLIB

    if(mod(m_flushed,10) .eq. 0) then
       flush(m_OUTPUTUNIT_TimeProfile)
       m_flushed = m_flushed + 1
    end if

  end subroutine OutPutTimeDebug

  !***************Time Debug*******************************************

end module MCLIB_TimeProfile
