!*********************************************************************************!
!--- Description:
!--- Author : Lei Zhai, Insti. of Nucle. Sci. and Tech., Sichuan University
!--- Email : zhaileiytp@163.com
!--- data: From 2017-09 to 2021-12
!--- License: MIT License (There are no limitation for anyone to use/modify/sale of this code, be happy to use this code)
!--- Please ref "Lei Zhai, Chaoqiong Ma, Jiechao Cui and Qing Hou, GPU-based acceleration of Monte Carlo simulations for migration-coalescence evolution of gas bubbles in materials
!---                        Modelling Simul. Mater. Sci. Eng. 2019. 27 055008,https://iopscience.iop.org/article/10.1088/1361-651X/ab1d14
!*********************************************************************************!
!
!  MC_MultiBoxToOneBox_Assemble.F90
!
!  Free-Format Fortran Source File
!  Generated by PGI Visual Fortran(R)
!  1/9/2018 11:29:57 AM
!
program MC_MultiBox2Box_Assemble_Main
  implicit none

  !-----------Vars---------------
  character*256::ARG
  character*128::filePath
  integer::arg_Num
  !-----------Body--------------
  arg_Num = COMMAND_ARGUMENT_COUNT()

  if(arg_NUM .GE. 1) then

    call GET_COMMAND_ARGUMENT(0,ARG)

    call GET_COMMAND_ARGUMENT(1,ARG)
    Read(ARG,*) filePath

  end if

  return

end program MC_MultiBox2Box_Assemble_Main
