!
!  MC_MultiBoxToOneBox_Assemble.F90
!
!  Free-Format Fortran Source File
!  Generated by PGI Visual Fortran(R)
!  1/9/2018 11:29:57 AM
!
program MC_MultiBox2Box_Assemble_Main
  implicit none

  !-----------Vars---------------
  character*256::ARG
  character*128::filePath
  integer::arg_Num
  !-----------Body--------------
  arg_Num = COMMAND_ARGUMENT_COUNT()

  if(arg_NUM .GE. 1) then

    call GET_COMMAND_ARGUMENT(0,ARG)

    call GET_COMMAND_ARGUMENT(1,ARG)
    Read(ARG,*) filePath

  end if

  return

end program MC_MultiBox2Box_Assemble_Main
